version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/auth-db
      - JWT_SECRET=supersecretkey123
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
